config/routes.rb
AdventureLibrary::Application.routes.draw do
  resources :libraries, :only => [:index]
  resources :adventures do
    resources :pages
  end
post '/adventures/scrape', to: 'adventures#scrape', as: 'adventures_scrape'
root 'adventures#index'
#              Prefix Verb   URI Pattern                                        Controller#Action
#           libraries GET    /libraries(.:format)                               libraries#index
#     adventure_pages GET    /adventures/:adventure_id/pages(.:format)          pages#index
#                     POST   /adventures/:adventure_id/pages(.:format)          pages#create
#  new_adventure_page GET    /adventures/:adventure_id/pages/new(.:format)      pages#new
# edit_adventure_page GET    /adventures/:adventure_id/pages/:id/edit(.:format) pages#edit
#      adventure_page GET    /adventures/:adventure_id/pages/:id(.:format)      pages#show
#                     PATCH  /adventures/:adventure_id/pages/:id(.:format)      pages#update
#                     PUT    /adventures/:adventure_id/pages/:id(.:format)      pages#update
#                     DELETE /adventures/:adventure_id/pages/:id(.:format)      pages#destroy
#          adventures GET    /adventures(.:format)                              adventures#index
#                     POST   /adventures(.:format)                              adventures#create
#       new_adventure GET    /adventures/new(.:format)                          adventures#new
#      edit_adventure GET    /adventures/:id/edit(.:format)                     adventures#edit
#           adventure GET    /adventures/:id(.:format)                          adventures#show
#                     PATCH  /adventures/:id(.:format)                          adventures#update
#                     PUT    /adventures/:id(.:format)                          adventures#update
#                     DELETE /adventures/:id(.:format)                          adventures#destroy
#                root GET    /                                                  adventures#index

end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
  belongs_to :library
  has_many :pages
  accepts_nested_attributes_for :pages
  before_save :create_guid
  validates :guid, uniqueness: true
  validates :title, presence: true
  validates :author, presence: true

  def create_guid
    self.guid ||= SecureRandom.urlsafe_base64(10)
  end
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_action :load_adventure_by_id, only: [:show, :edit, :update, :destroy]
  
  def index
    @adventures = Adventure.all.where.not(library_id: nil)
    @my_adventures = Adventure.all.where(library_id: nil)
    respond_to do |format|
      format.json { render :json => { adventures: @my_adventures.as_json(only: [:guid, :title, :author, :created_at, :updated_at], include: { :pages => {only: [:name, :text]} })}, status: :ok }
      format.html { render :index }
    end
  end
  
  def scrape
    url = params["link"]["url"]
    if url.include?("http://") && url.include?("heroku")
      LibrariesWorker.perform_async(url)
      flash[:sucess] = "Libraries are being scraped from the URL you entered"
      redirect_to root_path
    else
      flash[:error] = "Please enter a real url from Heroku"
      redirect_to root_path
    end
  end

  def show
    @pages = @adventure.pages
  end

  def new
    @adventure = Adventure.new
  end

  def create
    adventure = Adventure.new adventure_params
    if adventure.save
      adventure.pages.create(name: params["adventure"]["pages_attributes"]["0"]["name"], text: params["adventure"]["pages_attributes"]["0"]["text"])
      flash[:success] = "Adventure Created. Add more pages."
      redirect_to new_adventure_page_path(adventure)
    else
      flash[:error] = "You didn't do that correctly. Try again."
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    if @adventure.update_attributes adventure_params
    else
    end
    redirect_to adventure_path
  end

  def destroy
    @adventure.destroy
    redirect_to root_path
  end

private
  def adventure_params
    params.require(:adventure).permit(:title, :author)
  end

  def load_adventure_by_id
    @adventure = Adventure.find(params[:id])
  end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/views/adventures/_bad_index_entry.html.erb
<li>
<%= bad_index_entry.title %>
<% if bad_index_entry.library_id %>
  from:
  <%= link_to(bad_index_entry.library.url, bad_index_entry.library.url) %>
<% end %>
</li>

app/views/adventures/_form.html.erb
<br /><%= form_for @adventure do |f| %>
  <%= f.text_field :author, placeholder: '(Author)Who Are You?' %><br /><br />
  <%= f.text_field :title, placeholder: "Adventure Title" %><br />
  <%= f.fields_for :pages, @page do |b| %>
    <%= b.hidden_field :name, value: "start" %><br />
    <%= b.text_area :text, placeholder: "Start your adventure here" %><br />
  <% end %><br />
   <button type="submit" class="btn btn-success">What Happens Next?</button>  
<% end %>

app/views/adventures/_index_entry.html.erb
<li>
<%= link_to(index_entry.title,
           adventure_page_path(index_entry, index_entry.start)) %>
<% if index_entry.library_id %>
  from:
  <%= link_to(index_entry.library.url, index_entry.library.url) %>
<% end %>
</li>

app/views/adventures/_scrape_form.html.erb
<%= form_for Library.new do |f| %>
 
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url, id => "url", :placeholder => "enter url", :autofocus => true %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/adventures/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdventureLibrary</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/adventures/edit.html.erb
<%= form_for @adventure do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.fields_for :pages, @adventure.pages.build do |b| %>
    <%= b.hidden_field(name: "start") %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/adventures/index.html.erb
<h1>My Adventures</h1>
<% @my_adventures.each do |a| %>
  <li><%= link_to "'#{a.title}'", adventure_pages_path(a.id) %></li>
<% end %>

<h1>All the Adventures I know</h1>
<% @adventures.each do |ad| %>
  <li><%= link_to "'#{ad.title}'", adventure_pages_path(ad.id) %></li>
<% end %>

<br><br><br><p><%= link_to "Add a new adventure", new_adventure_path %></p>

<h5> Enter a URL to scrape here </h5>
<%= form_for :link, :url => adventures_scrape_path, :html => {:method => :post} do |f| %>
  <%= f.label :url %>
  <%= f.text_field :url, placeholder: 'Start with http://' %>
  <%= f.submit %>
<% end %>

app/views/adventures/new.html.erb
<%= form_for @adventure do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author, placeholder: "Your name" %>
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: "Title of this adventure" %>
  <%= f.fields_for :pages, @adventure.pages.build do |b| %>
    <%= b.hidden_field :name, :value => "start" %>
    <%= b.label :text %>
    <%= b.text_area :text, placeholder: "Enter the content of your starting page" %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/adventures/show.html.erb
hello world!