config/routes.rb
AdventureLibrary::Application.routes.draw do
  resources :libraries, :only => [:index]
  resources :adventures do
    resources :pages
  end
post '/adventures/scrape', to: 'adventures#scrape', as: 'adventures_scrape'
root 'adventures#index'
#              Prefix Verb   URI Pattern                                        Controller#Action
#           libraries GET    /libraries(.:format)                               libraries#index
#     adventure_pages GET    /adventures/:adventure_id/pages(.:format)          pages#index
#                     POST   /adventures/:adventure_id/pages(.:format)          pages#create
#  new_adventure_page GET    /adventures/:adventure_id/pages/new(.:format)      pages#new
# edit_adventure_page GET    /adventures/:adventure_id/pages/:id/edit(.:format) pages#edit
#      adventure_page GET    /adventures/:adventure_id/pages/:id(.:format)      pages#show
#                     PATCH  /adventures/:adventure_id/pages/:id(.:format)      pages#update
#                     PUT    /adventures/:adventure_id/pages/:id(.:format)      pages#update
#                     DELETE /adventures/:adventure_id/pages/:id(.:format)      pages#destroy
#          adventures GET    /adventures(.:format)                              adventures#index
#                     POST   /adventures(.:format)                              adventures#create
#       new_adventure GET    /adventures/new(.:format)                          adventures#new
#      edit_adventure GET    /adventures/:id/edit(.:format)                     adventures#edit
#           adventure GET    /adventures/:id(.:format)                          adventures#show
#                     PATCH  /adventures/:id(.:format)                          adventures#update
#                     PUT    /adventures/:id(.:format)                          adventures#update
#                     DELETE /adventures/:id(.:format)                          adventures#destroy
#                root GET    /                                                  adventures#index

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    <a class="navbar-brand" href="/">Waterfall Adventures</a>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar">ddd</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div class="navbar-header navbar-right">
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdventureLibrary</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <%flash.each do|key,value|%>
        <div class="alert alert-<%=key%>"> <%=value%> </div>
      <%end%>
    </div>
  </div>

  <%= yield %>
</div>

</body>
</html>

app/views/layouts/index.html.erb
<!-- #index.html.erb -->

<%= link_to 'Create an Adnventure', new_adventure_path %> <br /><br />

<% @adventures.each do |adventure| %>

<%= link_to adventure.title, adventure_path(adventure) %> by: <%= adventure.author %> <br />

<h4>Add your Library</h4>
  <%= form_for 'add URL' do |f| %>
  <%= f.text.field :url, placeholder: 'Enter Url' %><br />
  <%= f.submit 'Submit' %>
  <% end %>

app/views/layouts/show.html.erb
<!-- show.html.erb -->

<h1> Your Adventure Here </h1>
<p>by: <%= @adventure.author %> <br />

  <%= link_to 'Edit', edit_adventure_path(@adventure) %>br />
  <% link_to 'Delete',  adventure_path(@adventure),  method: 'delete', data: { confirm: "Are you sure?"} %> <br />

  <%= link_to "All Adventures", root_path %>